
services:
  # Service 1: The PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: karigar-postgres-db
    restart: always
    environment:
      POSTGRES_USER: karigar_user
      POSTGRES_PASSWORD: karigar_secure_password
      POSTGRES_DB: karigar_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service 2: The Redis Cache
  cache:
    image: redis:alpine
    container_name: karigar-redis-cache
    restart: always
    ports:
      - "6379:6379"

  # Service 3: Your Local Express Backend API
  api:
    build: .
    container_name: karigar-backend-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
        - .env
    environment:
      - PORT=3000
      # CRITICAL: Point 'localhost' to the service name 'cache'
      - REDIS_URL=redis://cache:6379
      # CRITICAL: Point 'localhost' to the service name 'db' 
      - DATABASE_URL=postgresql://karigar_user:karigar_secure_password@db:5432/karigar_database?schema=public
    depends_on:
      - db
      - cache

# Persist DB records on your host machine so data doesn't wipe when containers stop
volumes:
  postgres_data:
